---
- name: "Install libselinux-python"
  yum: "name=libselinux-python state=present"

- name: "Disable SELinux"
  become: yes
  selinux: "state=disabled"

- name: "Setup iptables"
  template: "backup=yes src=iptables.j2 dest=/etc/sysconfig/iptables"
  notify:
    - "restart iptables"

- name: "Allow http and https"
  blockinfile:
    dest: "/etc/sysconfig/iptables"
    create: yes
    backup: yes
    insertafter: "# ansible blockinfile"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
    block: "-A RH-Firewall-1-INPUT -m state --state NEW -m tcp -p tcp --dport {{ item }} -j ACCEPT"
  with_items:
    - 80
    - 443
  notify:
    - "restart iptables"

- name: "yum update"
  yum: "name=* state=latest disable_gpg_check=yes"

