---
- name: "Install libselinux-python"
  yum: "name=libselinux-python state=installed"

- name: "Disable SELinux"
  become: yes
  selinux: "state=disabled"

- name: "Setup iptables"
  template: "backup=yes src=iptables.j2 dest=/etc/sysconfig/iptables"
  notify:
    - "restart iptables"

- name: "yum update"
  yum: "name=* state=latest disable_gpg_check=yes"

